name: get_tracker_list

on:
    schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get latest tracker list and compress
      run: |
        bash -c "./trackers.sh . trackers.list"
        find . -name "*trackers*"

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: trackers.list
        path: trackers.list
        retention-days: 1
